java_library(
    name = "scala-java8-compat-2-13",
    exports = [
        "//external:jar/org/scala-lang/modules/scala-java8-compat-2-13"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/scala-lang:scala-library"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


